chore: update CI for 3.11 and 3.12
openedx/DoneXBlock pull request #207
Opened 2024-02-14 10:36 UTC by salman2013

2024-02-14 15:05 UTC, feanil reviewed
Looks like everything is passing on the newer versions, can you update the classifiers in setup.py as a part of this PR as well? Then I think we can merge and release this.

2024-02-15 07:19 UTC, salman2013 commented
@feanil i have updated the classifiers.

2024-02-20 12:26 UTC, farhan commented on .github/workflows/ci.yml
> -        toxenv: [py38-django32, py38-django42, quality]
Should we also remove the django32 support from all the repositories?

2024-02-20 12:26 UTC, farhan commented on setup.py
>          'Programming Language :: Python :: 3',
I think we should drop their support as well
All repositories should only give support for `v3.8`, `v3.11` and `v3.12`

2024-02-22 12:04 UTC, salman2013 commented on .github/workflows/ci.yml
> -        toxenv: [py38-django32, py38-django42, quality]
yes, we are doing this along this task.

2024-02-22 12:05 UTC, salman2013 commented on setup.py
>          'Programming Language :: Python :: 3',
As per Feanil's direction we have to keep this.

2024-02-26 10:02 UTC, farhan commented on setup.py
>          'Programming Language :: Python :: 3',
We should remove python 2 classifier as recommended here
https://openedx.slack.com/archives/C05P7KQURL0/p1708438058899899?thread_ts=1708432662.032769&cid=C05P7KQURL0

2024-02-26 10:03 UTC, farhan requested changes
1 change

2024-02-27 10:18 UTC, salman2013 commented on setup.py
>          'Programming Language :: Python :: 3',
@farhan I have fixed the above comment.

2024-02-27 14:23 UTC, farhan approved these changes

2024-02-29 11:15 UTC, merged